atlassian/__init__.py,sha256=-iSy-LENEBf5tr7mZW6hmLTX8jQwVaDMkkctHzKuzr0,54
atlassian/client.py,sha256=qt-jJ_bvzR3IPUDGbqEsk1DmysQ9elJ6ykKuOMxtiqU,1765
atlassian/error.py,sha256=3rm_uYUaGggiNos0n70Mnb8LSU5tffINZJrCt6NUct8,1669
atlassian/jira.py,sha256=ipehDi6xedB4IEY3hRuIen6hNtLN2D1BJXxJJ6LBuIA,796
atlassian/logger.py,sha256=TPflzcIqPj0jqEpnySul0hD0Xis-jpr7fe7mzCKTXqk,1105
atlassian_api_py-0.0.3.dist-info/METADATA,sha256=bD_VFcNpltzpFmTyBRKD6c7M4k_8_Y2I7HUaxXTTHyk,2362
atlassian_api_py-0.0.3.dist-info/WHEEL,sha256=YUYzQ6UQdoqxXjimOitTqynltBCkwY6qlTfTh2IzqQU,97
atlassian_api_py-0.0.3.dist-info/top_level.txt,sha256=84-EDv8LNaZx01TCGjBzglwPU1JSRJ7fPSq9uy55Sv0,10
atlassian_api_py-0.0.3.dist-info/RECORD,,
